export const planDefinitions = [
  {
    code: "free",
    name: "Gratis",
    description: "Plan gratuito para operacion basica de una tortilleria.",
  },
  {
    code: "paid",
    name: "Pago",
    description: "Plan comercial con facturacion, rutas, multi-sucursal y reportes avanzados.",
  },
] as const;

export const commercialPlanDefinitions = [
  {
    code: "mostrador",
    name: "Mostrador",
    description: "Plan piloto Mostrador: 1 sucursal, 1 POS, 1 terminal, sin CFDI.",
    price: "299.00",
    includedBranches: 1,
    includedPos: 1,
    includedTerminals: 1,
    includedCfdi: 0,
    routesEnabled: false,
    billingCfdiEnabled: false,
    advancedReportsEnabled: false,
  },
  {
    code: "operativo",
    name: "Operativo",
    description: "Plan piloto Operativo: 1 sucursal, 2 POS, 2 terminales, 50 CFDI.",
    price: "599.00",
    includedBranches: 1,
    includedPos: 2,
    includedTerminals: 2,
    includedCfdi: 50,
    routesEnabled: false,
    billingCfdiEnabled: true,
    advancedReportsEnabled: false,
  },
  {
    code: "comercial",
    name: "Comercial",
    description: "Plan piloto Comercial: 2 sucursales, 3 POS, 3 terminales, 100 CFDI y rutas.",
    price: "999.00",
    includedBranches: 2,
    includedPos: 3,
    includedTerminals: 3,
    includedCfdi: 100,
    routesEnabled: true,
    billingCfdiEnabled: true,
    advancedReportsEnabled: true,
  },
] as const;

export const featureDefinitions = [
  ["pos_basic", "POS basico", null],
  ["cash_control", "Control de caja", null],
  ["inventory_basic", "Inventario basico", null],
  ["production_control", "Produccion diaria", null],
  ["customer_credit", "Credito a clientes", null],
  ["billing_cfdi", "Facturacion CFDI", null],
  ["multi_branch", "Multi-sucursal", null],
  ["delivery_routes", "Rutas de reparto", null],
  ["reconciliation", "Conciliacion de pagos", null],
  ["advanced_reports", "Reportes avanzados", null],
  ["max_users", "Maximo de usuarios", 3],
  ["max_branches", "Maximo de sucursales", 1],
  ["max_pos_devices", "Maximo de POS", 1],
] as const;

export const freePlanEnabledFeatures = ["pos_basic", "cash_control", "inventory_basic", "production_control"] as const;

export const roleDefinitions = [
  ["platform_owner", "Duenio de Plataforma", "platform"],
  ["organization_owner", "Duenio de Organizacion", "organization"],
  ["manager", "Gerente", "organization"],
  ["supervisor", "Supervisor", "branch"],
  ["cashier", "Cajero", "branch"],
] as const;

export const permissionDefinitions = [
  ["sales.create", "Crear ventas"],
  ["sales.view", "Ver ventas"],
  ["sales.cancel_before_payment", "Cancelar ticket antes de pago"],
  ["sales.cancel_after_payment", "Cancelar venta cobrada"],
  ["payments.create", "Registrar pagos"],
  ["payments.cancel_terminal_order", "Cancelar cobros con terminal"],
  ["payments.manual_card_reference", "Usar folio manual de tarjeta"],
  ["integrations.view", "Ver integraciones"],
  ["integrations.manage", "Gestionar integraciones"],
  ["cash.open", "Abrir caja"],
  ["cash.close", "Cerrar caja"],
  ["cash.movements.view", "Ver movimientos de caja"],
  ["cash.withdraw.request", "Solicitar retiro"],
  ["cash.withdraw.authorize", "Autorizar retiro"],
  ["cash.adjust", "Ajustar caja"],
  ["organization.view", "Ver organizacion"],
  ["organization.update", "Actualizar organizacion"],
  ["branches.view", "Ver sucursales"],
  ["branches.manage", "Gestionar sucursales"],
  ["users.view", "Ver usuarios"],
  ["users.manage", "Gestionar usuarios"],
  ["inventory.view", "Ver inventario"],
  ["inventory.manage", "Gestionar inventario"],
  ["production.manage", "Gestionar produccion"],
  ["products.view", "Ver productos"],
  ["products.manage", "Gestionar productos"],
  ["prices.manage", "Gestionar precios"],
  ["customers.view", "Ver clientes"],
  ["customers.manage", "Gestionar clientes"],
  ["customers.credit.manage", "Gestionar credito de clientes"],
  ["routes.view", "Ver rutas"],
  ["billing.manage", "Gestionar facturacion"],
  ["billing.view", "Ver facturacion"],
  ["routes.manage", "Gestionar rutas"],
  ["reports.basic.view", "Ver reportes basicos"],
  ["reports.advanced.view", "Ver reportes avanzados"],
  ["audit.view", "Ver auditoria"],
  ["platform.dashboard.view", "Ver dashboard de plataforma"],
  ["platform.organizations.view", "Ver organizaciones de plataforma"],
  ["platform.organizations.manage", "Gestionar organizaciones de plataforma"],
  ["platform.organizations.suspend", "Suspender organizaciones"],
  ["platform.subscriptions.view", "Ver suscripciones de plataforma"],
  ["platform.subscriptions.manage", "Gestionar suscripciones de plataforma"],
  ["platform.payments.view", "Ver pagos SaaS"],
  ["platform.payments.manage", "Gestionar pagos SaaS"],
  ["platform.pos_devices.view", "Ver POS de plataforma"],
  ["platform.pos_devices.manage", "Gestionar POS de plataforma"],
  ["platform.pos_devices.license", "Licenciar POS"],
  ["platform.audit.view", "Ver auditoria global"],
  ["platform.support.access", "Acceder a soporte de plataforma"],
  ["platform.impersonation.start", "Iniciar impersonacion"],
  ["platform.impersonation.end", "Terminar impersonacion"],
] as const;

export const rolePermissionMatrix = {
  platform_owner: permissionDefinitions
    .map(([code]) => code)
    .filter((code) => code.startsWith("platform.")),
  organization_owner: [
    "organization.view",
    "organization.update",
    "branches.view",
    "branches.manage",
    "users.view",
    "users.manage",
    "sales.view",
    "cash.movements.view",
    "inventory.view",
    "inventory.manage",
    "production.manage",
    "products.view",
    "products.manage",
    "prices.manage",
    "customers.view",
    "customers.manage",
    "customers.credit.manage",
    "routes.view",
    "routes.manage",
    "billing.view",
    "billing.manage",
    "reports.basic.view",
    "reports.advanced.view",
    "audit.view",
    "integrations.view",
    "integrations.manage",
  ],
  manager: [
    "branches.view",
    "sales.create",
    "sales.view",
    "sales.cancel_before_payment",
    "sales.cancel_after_payment",
    "payments.create",
    "payments.cancel_terminal_order",
    "payments.manual_card_reference",
    "cash.open",
    "cash.close",
    "cash.movements.view",
    "cash.withdraw.request",
    "cash.withdraw.authorize",
    "cash.adjust",
    "inventory.view",
    "inventory.manage",
    "production.manage",
    "products.view",
    "products.manage",
    "prices.manage",
    "customers.view",
    "customers.manage",
    "customers.credit.manage",
    "routes.view",
    "routes.manage",
    "reports.basic.view",
    "reports.advanced.view",
    "integrations.view",
  ],
  supervisor: [
    "sales.create",
    "sales.view",
    "sales.cancel_before_payment",
    "payments.create",
    "payments.cancel_terminal_order",
    "cash.open",
    "cash.close",
    "cash.movements.view",
    "cash.withdraw.request",
    "cash.withdraw.authorize",
    "inventory.view",
    "inventory.manage",
    "production.manage",
    "products.view",
    "prices.manage",
    "customers.view",
    "reports.basic.view",
  ],
  cashier: [
    "sales.create",
    "sales.view",
    "sales.cancel_before_payment",
    "payments.create",
    "cash.open",
    "cash.close",
    "cash.movements.view",
    "cash.withdraw.request",
    "inventory.view",
    "products.view",
    "customers.view",
  ],
} as const;
